working_directory = "/home/user/Documents"

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[font]
size = 13.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }

